### ISSUE TITLE
composer fails

### ISSUE THREAD

**Issue by exebece** [brunohsouza/weather-cli-app#1]
hi, wanted to have a look at it. doing composer install bring me to some error messages. pls check your composer.lock when I removed it composer install was ok. but then:

 Unrecognized option "http_version" under "framework.http_client". Available  
!!     options are "default_options", "enabled", "max_host_connections", "scoped_  
!!    clients".

seems to be some sort of versions mismatch?

**Comment by brunohsouza** [comment]
Hi Luca,

Thank you very much for getting in contact with me. Yes, it seems to be
regarding the Symfony framework version due to some parameters being
available in the version 5.2 which are not present in the former version.

In any case, I'll take a look at this soon and fix this issue.

Kind regards,

**Comment by brunohsouza** [comment]
Hi,

I finally had some time to take a look on this again and to solve the issue with the http_version configuration for Symfony 5.2. The issue was that om Symfony 5.2 the http_version is inside the default_options parameter in framework.yaml configuration.

In this case, the configs will be like this: 

![image](https://user-images.githubusercontent.com/12256585/106830412-fa3e4300-6685-11eb-919c-d1eddb5922a0.png)

I also deleted my composer.lock and vendor directory to test the issue with composer and it is running successfully now after fix this issue.
